#!/usr/bin/env bash
# Command to make an nginx server listen on port 80, shorter version
response=$(curl -Is http://localhost:80 | head -n 1)
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
pkill -1 nginx
